server:
  port: 9070

spring:
  application:
    name: rabbitmq-microservices
  datasource:
    url: jdbc:h2:mem:rabbit-db
    driverClassName: org.h2.Driver
  h2:
    console:
      enable: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
